// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIeXlJRwxnZqFJMF0PMbBSgybBkDubjQ',
    appId: '1:852444389483:web:2043718d3e19082327912e',
    messagingSenderId: '852444389483',
    projectId: 'logintpm',
    authDomain: 'logintpm.firebaseapp.com',
    storageBucket: 'logintpm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT5c_VMFbSkVvYwkD-5dYPWF-_2jLVZZA',
    appId: '1:852444389483:android:5a3d196b417c601327912e',
    messagingSenderId: '852444389483',
    projectId: 'logintpm',
    storageBucket: 'logintpm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2MPqHRzcF4KOTrBKxQTdb3Mg7J75Ox1c',
    appId: '1:852444389483:ios:fe7e750871cc5efa27912e',
    messagingSenderId: '852444389483',
    projectId: 'logintpm',
    storageBucket: 'logintpm.appspot.com',
    iosClientId: '852444389483-lqufuc9mjulbd2ibsr5pr3ue028kl30h.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktpm1',
  );
}
